#!/bin/sh -
#
# Copyright 2023 OK Ryoko
# SPDX-License-Identifier: BSD-2-Clause
#
# SYNOPSIS:
#
#   ./release.sh [-h] VERSION
#
# DESCRIPTION:
#
#   Build an image containing a bootstrapped environment for containers based on
#   Chimera Linux for each supported architecture
#
#   Add each image to a multi-architecture image index
#
#   Push the index and images to ghcr.io/ok-ryoko/chimera:VERSION and
#   ghcr.io/ok-ryoko/chimera:latest
#
# REQUIREMENTS:
#
#   - Working Internet connection
#   - Authentication to ghcr.io/ok-ryoko
#   - Authorization to write packages to ghcr.io/ok-ryoko
#   - Buildah
#   - build.sh (included)
#
# NOTES:
#
#   Consumes the images generated by build.sh automatically
#
#   Does not clean up intermediate entities such as containers and images in the
#   event of an error

set -o errexit
set -o nounset

usage() {
	printf 'usage: %s [-h] VERSION\n' "$0"
}

error() {
	printf '%s: error: %s\n' "$0" "$1"
	exit 1
}

while getopts 'h' opt; do
	case "${opt}" in
		h) usage && exit 0 ;;
		?) usage && exit 2 ;;
	esac
done
shift $((OPTIND-1))

readonly chimera_version="${1:?$(usage && exit 2)}"
readonly domain='ghcr.io'
readonly namespace='ok-ryoko'
readonly path="${namespace}/chimera"
readonly repository="${domain}/${path}"

buildah login --get-login "${domain}/${namespace}" > '/dev/null'

readonly manifest="${repository}:${chimera_version}"
readonly manifest_latest="${repository}:latest"

for m in "${manifest}" "${manifest_latest}"; do
	if buildah manifest exists "${m}"; then
		error "manifest ${m} already exists"
	fi
done
unset -v m

export BUILDAH_FORMAT='oci'

printf '%s\n' "Creating manifest ${manifest}..."
buildah manifest create "${manifest}"

readonly label_authors='OK Ryoko <ryoko@kyomu.jp.net>'
readonly label_source="https://github.com/${path}"

readonly arches='aarch64 ppc64 ppc64le riscv64 x86_64'
# shellcheck disable=SC2086
for arch in $arches; do
	ref="${manifest}-${arch}"
	printf '%s\n' "Building image ${ref}..."
	img="$(./scripts/build.sh -a "${arch}" "${chimera_version}")"
	ctr="$(buildah from "${img}")"
	buildah config \
		--annotation='org.opencontainers.image.base.name-' \
		--annotation='org.opencontainers.image.base.digest-' \
		--label "org.opencontainers.image.created=$(date --rfc-3339=ns --utc)" \
		--label "org.opencontainers.image.authors=${label_authors}" \
		--label "org.opencontainers.image.source=${label_source}" \
		--label "org.opencontainers.image.ref.name=${ref}" \
		"${ctr}"
	buildah commit \
		--manifest "${manifest}" \
		--omit-history \
		--squash \
		"${ctr}" \
		"${ref}"
	buildah rm "${ctr}" && buildah rmi "${img}"
done
unset -v arch

printf '%s\n' "Pushing manifest ${manifest}..."
buildah manifest push \
	--all \
	--tls-verify \
	"${manifest}" \
	"docker://${manifest}"

buildah tag "${manifest}" "${manifest_latest}"
printf '%s\n' "Pushing manifest ${manifest_latest}..."
buildah manifest push \
	--all \
	--rm \
	--tls-verify \
	"${manifest_latest}" \
	"docker://${manifest_latest}"

exit 0
