name: release
on:
  workflow_dispatch:

permissions:
  packages: write

env:
  CHIMERA_VERSION: 20231227

jobs:
  release:
    runs-on:
      - ubuntu-22.04

    steps:
      - name: Checkout last commit on branch main
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Chimera Linux container images
        run: sudo ./scripts/release_wrapper.sh "${CHIMERA_VERSION}"
